version: "4.0"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: "tinurl"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"